class Constants:
    SMALL_BOARD_SIZE = 6
    LARGE_BOARD_SIZE = 10
    NUMBER_OF_ROCKS_IN_SMALL_BOARD = 32
    NUMBER_OF_ROCKS_IN_LARGE_BOARD = 92
    EMPTY_CELL_VAL = 0
    BLACK_AMAZON_VAL = 1
    WHITE_AMAZON_VAL = 2
    BLOCKED_CELL_VAL = 3
    OPONNENT_MODE = 1
    ONE_ON_ONE = 2
    COLUMNS_ARRAY = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"]
